### ISSUE TITLE
ASB 2018.01

### ISSUE THREAD

**Issue by hahnjo** [cm12-amami/discussion#11]
@Micha-Btz @MSe1969 
Happy new year, the story continues. Links available, no patches yet:
https://source.android.com/security/bulletin/2018-01-01
https://source.android.com/security/bulletin/pixel/2018-01-01

I'll try to help with the kernel patches this time again...

**Comment by Micha-Btz** [comment]
https://developer.arm.com/support/security-update

This is really awful. But we have a ARMv7 v71 and if is the table on the link right, we are not affected.

**Comment by hahnjo** [comment]
@Micha-Btz the table does not list instruction sets. According to https://en.wikipedia.org/wiki/Krait_(CPU) each core is similar to a Cortex-A15 which is affected.

**Comment by hahnjo** [comment]
Kernel:
- [ ] CVE-2017-14497 - fixes commit introduced in Linux 4.6 (https://github.com/torvalds/linux/commit/58d19b19cd99)
- [x] CVE-2017-13215
- [x] CVE-2017-13216 - no public patch
- [ ] CVE-2017-13218 - no public patch

Qualcomm:
- [ ] CVE-2017-15849 - needs to be done in hardware/qcom/display-caf/msm8974
- [ ] CVE-2017-11069 - we can't update the bootloader

Pixel - Kernel:
- [ ] CVE-2017-13219 - no public patch
- [ ] CVE-2017-13220 - no public patch
- [ ] CVE-2017-13221 - no public patch
- [ ] CVE-2017-11473 - not relevant (x86)
- [ ] CVE-2017-13222 - no public patch
- [x] CVE-2017-14140
- [ ] CVE-2017-15537 - not relevant (x86)

**Comment by hahnjo** [comment]
Pixel - Qualcomm:
- [ ] CVE-2017-9705 - file does not exist
- [ ] CVE-2017-15847 - files does not exist
- [ ] CVE-2017-15848 - case does not exist
- [ ] CVE-2017-11081 - functions do not exist, but I fixed another occurrence of this overflow
- [x] CVE-2017-15845
- [ ] CVE-2017-14873 - file does not exist
- [x] CVE-2017-11035 - was already applied, but I moved the `MIN` statement to the correct case
- [ ] CVE-2017-11003 - we can't update the bootloader
- [ ] CVE-2017-9689 - can't find file to patch (not in kernel)
- [ ] CVE-2017-14879 - no public patch
- [ ] CVE-2017-11080 - we can't update the bootloader
- [ ] CVE-2017-14869 - we can't update the bootloader
- [ ] CVE-2017-11066 - we can't update the bootloader
- [ ] CVE-2017-15850 - no public patch
- [x] CVE-2017-9712
- [ ] CVE-2017-11079 - we can't update the bootloader
- [ ] CVE-2017-14870 - we can't update the bootloader
- [ ] CVE-2017-11079 - we can't update the bootloader

**Comment by hahnjo** [comment]
The kernel booted fine on my device, so I've pushed the commits to `cm-12.1-test`.

CVE-2017-15849 needs to be applied to `hardware/qcom/display-caf/msm8974`!

**Comment by MSe1969** [comment]
Hi, 
as an interim step, I have brought all to 2018-01-01 (w/o Pixel/Nexus, yet) in cm-12.1-test.
Why? 
In **external/libhevc**, I had to pick a couple of significant upstream commits before I was able to apply the ASB patches, so this deserves some testing before continuing, especially, because also the Pixel/Nexus bulletin has many libhevc patches. It seems that this ASB consists of 70% libhevc patches...
Doing now a test build (hope it even compiles... ;))

**Comment by Micha-Btz** [comment]
hey,
i don't have time to help with the patches this month, but I want to help testing. But i can't compile the rom.
```
target thumb C++: libstagefright_soft_hevcdec <= frameworks/av/media/libstagefright/codecs/hevcdec/SoftHEVC.cpp
target arm C: libhevcdec <= external/libhevc/decoder/ihevcd_utils.c
target arm C: libhevcdec <= external/libhevc/decoder/ihevcd_get_mv.c
target arm C: libhevcdec <= external/libhevc/decoder/ihevcd_mv_pred.c
target arm C: libhevcdec <= external/libhevc/decoder/ihevcd_mv_merge.c
external/libhevc/decoder/ihevcd_utils.c: In function 'ihevcd_parse_pic_init':
external/libhevc/decoder/ihevcd_utils.c:1023:29: error: 'mv_buf_t' has no member named 'l0_collocated_poc'
             memset(ps_mv_buf->l0_collocated_poc, 0, sizeof(ps_mv_buf->l0_collocated_poc));
                             ^
external/libhevc/decoder/ihevcd_utils.c:1023:69: error: 'mv_buf_t' has no member named 'l0_collocated_poc'
             memset(ps_mv_buf->l0_collocated_poc, 0, sizeof(ps_mv_buf->l0_collocated_poc));
                                                                     ^
external/libhevc/decoder/ihevcd_utils.c:1024:29: error: 'mv_buf_t' has no member named 'u1_l0_collocated_poc_lt'
             memset(ps_mv_buf->u1_l0_collocated_poc_lt, 0, sizeof(ps_mv_buf->u1_l0_collocated_poc_lt));
                             ^
external/libhevc/decoder/ihevcd_utils.c:1024:75: error: 'mv_buf_t' has no member named 'u1_l0_collocated_poc_lt'
             memset(ps_mv_buf->u1_l0_collocated_poc_lt, 0, sizeof(ps_mv_buf->u1_l0_collocated_poc_lt));
                                                                           ^
external/libhevc/decoder/ihevcd_utils.c:1025:29: error: 'mv_buf_t' has no member named 'l1_collocated_poc'
             memset(ps_mv_buf->l1_collocated_poc, 0, sizeof(ps_mv_buf->l1_collocated_poc));
                             ^
external/libhevc/decoder/ihevcd_utils.c:1025:69: error: 'mv_buf_t' has no member named 'l1_collocated_poc'
             memset(ps_mv_buf->l1_collocated_poc, 0, sizeof(ps_mv_buf->l1_collocated_poc));
                                                                     ^
external/libhevc/decoder/ihevcd_utils.c:1026:29: error: 'mv_buf_t' has no member named 'u1_l1_collocated_poc_lt'
             memset(ps_mv_buf->u1_l1_collocated_poc_lt, 0, sizeof(ps_mv_buf->u1_l1_collocated_poc_lt));
                             ^
external/libhevc/decoder/ihevcd_utils.c:1026:75: error: 'mv_buf_t' has no member named 'u1_l1_collocated_poc_lt'
             memset(ps_mv_buf->u1_l1_collocated_poc_lt, 0, sizeof(ps_mv_buf->u1_l1_collocated_poc_lt));
                                                                           ^
build/core/binary.mk:699: die Regel für Ziel „/home/mdomann/handy/build/cm-12.1/out/target/product/amami/obj/STATIC_LIBRARIES/libhevcdec_intermediates/decoder/ihevcd_utils.o“ scheiterte
make: *** [/home/mdomann/handy/build/cm-12.1/out/target/product/amami/obj/STATIC_LIBRARIES/libhevcdec_intermediates/decoder/ihevcd_utils.o] Fehler 1
make: *** Es wird auf noch nicht beendete Prozesse gewartet...
make: Verzeichnis „/home/mdomann/handy/build/cm-12.1“ wird verlassen

#### make failed to build some targets (03:13 (mm:ss)) ####
```

**Comment by MSe1969** [comment]
Yes, having the same result, will look later today or tomorrow.

**Comment by MSe1969** [comment]
I think I have solved the issue, new test build running

**Comment by MSe1969** [comment]
ok compiled through - testing now

**Comment by Micha-Btz** [comment]
I have also done a build yesterday. Run's without problems.

**Comment by MSe1969** [comment]
Have pushed now also the Pixel/Nexus patches, **except for CVE-2017-0846**, which causes some trouble (NPE) in cm-13.0, so I don't expect it to work in cm-12.1 either. Further, I think that CVE-2017-15849 is not relevant for us, as we do not have an hwc2 subdirectory in hardware/qcom/display-caf/msm8974 and the whole change is about altering stuff in hwc2.
Whilst the test build is compiling, just saw an issue with CVE-2017-13212, need to look at that now...

**Comment by MSe1969** [comment]
okay, fixed the backport f. CVE-2017-13212 - test build compiling now properly
Please test - if all is okay, I'll also update the version string

**Comment by MSe1969** [comment]
Have also found and added CVE-2017-13165 A-31269937* ("not publicly available") from December Pixel/Nexus ASB (system/core)

**Comment by MSe1969** [comment]
Hi all, 
this is CVE-2017-13218  A-68266545* listed in the January ASB as "To provide additional protection, the update for CVE-2017-13218 included in this bulletin reduces access to high-precision timers, which helps limits side channel attacks (such as CVE-2017-5715, CVE-2017-5753, and CVE-2017-5754) of all known variants of ARM processors. "
https://android.googlesource.com/kernel/msm/+/286f446a2cc1cf0c07e8aa5180d9f910ea9bda49
This patch however would not apply to our kernel...
@hahnjo - any further opinion?

**Comment by MSe1969** [comment]
Also found and added CVE-2017-13216 A-66954097* - which is here:
https://android.googlesource.com/kernel/msm/+/e013bc2a6de7b3388d5ce0afd194fc20f5a7a6aa

**Comment by hahnjo** [comment]
Why can't Google properly link to these patches, why do we always need to search? Good job!

I think the code is in `arch/arm/include/asm/arch_timer.h`. I'm note sure how important this "mitigation" is as it only reduces access from user space, but we should test carefully just in case our "old" Android relies on it somewhere...

**Comment by MSe1969** [comment]
Good question...
Yes, correct - that is the place... - maybe we should defer that to the February ASB to have better time for testing etc.

By the way:
ASB 04-2017, CVE-2017-0564 ("not publicly available"):
https://android.googlesource.com/kernel/msm/+/e4e29ab1255f229a48c983d14f903f99eb2241a1
(implemented as well)

**Comment by MSe1969** [comment]
For the kernel, I have now started a more systematic approach:
```
git clone https://android.googlesource.com/kernel/msm/ google-msm
cd google-msm
git checkout tags/android-8.1.0_r0.17
```
And in the next days, I'll search the commits via the grep search, for example bug-ID A-32402548 (CVE-2017-0403 from January 2017 ASB) will be searched via `git log --grep="32402548"`  
This outputs for example
```
commit 1fe7366b4b255e43c424a13716b434b0c57f5444
Author: John Dias <joaodias@google.com>
Date:   Wed Nov 9 11:03:57 2016 -0800

    perf: don't leave group_entry on sibling list (use-after-free)
...
```
and with the commit hash, I can extract a patch file to see whether it is relevant. Unfortunately, this method works only for the kernel - it won't work for older branches of other repositories, but hey, if we can rewind 18 months and grab a lot of "not publicly available" kernel patches, Qualcomm updates etc., I think this is not bad :)
Maybe we can somehow split that work amongst us?

**Comment by hahnjo** [comment]
@MSe1969 interesting, I probably won't have much time the next week though.

Maybe we should release the current update first? I haven't built yet (my VM crashed...) but it seems to work for both of you...

**Comment by MSe1969** [comment]
okay, then I'll ship a build now and we'll continue working on the kernel afterwards

**Comment by MSe1969** [comment]
ASB has been shipped, test branch has been merged into stable branch, for CVE-2017-13218, a new issue has been opened, as well as for the other "not publicly available" stuff, therefore, closing this issue.
